In [7]:
df_old = pd.read_csv('../data/rag-eval-round2-old.csv')

In [1]:
import pandas as pd
df_question = pd.read_csv('../data/ground-truth-retrieval.csv')
df_question.head()

   chunk_id                                           question
0  604727_0  What is the origin of coffee consumption accor...
1  604727_0  Which two main types of coffee beans are menti...
2  604727_0  How has the global coffee industry economicall...
3  604727_0  What are some common ways coffee can be prepar...
4  604727_0  Where are coffee plants primarily cultivated a...

## Candidate prompts

`rag.prompt_template` (the current production default) vs. `prompt_template_v2`, which
explicitly allows the model to say "I don't know" when the context doesn't cover the question.

In [2]:
prompt_template_v2 = """
You're a coffee assistant. Answer the QUESTION based on the CONTEXT from our coffee database.
Use only the facts from the CONTEXT. If the CONTEXT doesn't contain enough information to answer, say "I don't know" instead of guessing.

QUESTION: {question}

CONTEXT:
{context}
""".strip()

In [3]:
import sys
sys.path.append('..')

from coffee_assistant import rag

In [4]:
df_sample = df_question.sample(n=100, random_state=1)
sample = df_sample.to_dict(orient='records')

## LLM-as-judge

`prompt2_template` asks gpt-4o-mini to classify a (question, generated answer) pair as
`NON_RELEVANT`, `PARTLY_RELEVANT`, or `RELEVANT`, returned as parsable JSON.

In [5]:
prompt2_template = """
You are an expert evaluator for a RAG system.
Your task is to analyze the relevance of the generated answer to the given question.
Based on the relevance of the generated answer, you will classify it
as "NON_RELEVANT", "PARTLY_RELEVANT", or "RELEVANT".

Here is the data for evaluation:

Question: {question}
Generated Answer: {answer_llm}

Please analyze the content and context of the generated answer in relation to the question
and provide your evaluation in parsable JSON without using code blocks:

{{
  "Relevance": "NON_RELEVANT" | "PARTLY_RELEVANT" | "RELEVANT",
  "Explanation": "[Provide a brief explanation for your evaluation]"
}}
""".strip()

## Evaluation pipeline

`evaluate_answers` generates an answer per sampled question with a given prompt template,
then judges it; `to_dataframe` flattens the results into a plain table.

In [6]:
from tqdm.auto import tqdm
import json 

def evaluate_answers(sample, prompt_template):
    evaluations = []

    for record in tqdm(sample):
        question = record['question']
        answer_llm = rag.rag(question, prompt_template=prompt_template)
    
        prompt = prompt2_template.format(
            question=question,
            answer_llm=answer_llm['answer']
        )
    
        evaluation, _ = rag.llm(prompt)
        evaluation = json.loads(evaluation)
        
        evaluations.append((record, answer_llm, evaluation))
    return evaluations

In [7]:
def to_dataframe(evaluations):
    df_eval = pd.DataFrame(evaluations, columns=['record', 'answer', 'evaluation'])
    
    df_eval['chunk_id'] = df_eval.record.apply(lambda d: d['chunk_id'])
    df_eval['question'] = df_eval.record.apply(lambda d: d['question'])
    
    df_eval['relevance'] = df_eval.evaluation.apply(lambda d: d['Relevance'])
    df_eval['explanation'] = df_eval.evaluation.apply(lambda d: d['Explanation'])
    
    del df_eval['record']
    del df_eval['evaluation']
    
    return df_eval

### Run both prompts

100 sampled questions per prompt, ~200 LLM calls total (100 generation + 100 judging) per prompt.

In [8]:
evaluations_default = evaluate_answers(sample, rag.prompt_template)
df_default = to_dataframe(evaluations_default)

evaluations_v2 = evaluate_answers(sample, prompt_template_v2)
df_v2 = to_dataframe(evaluations_v2)

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

## Relevance distribution

In [9]:
df_default.relevance.value_counts(normalize=True)

relevance
RELEVANT           0.97
PARTLY_RELEVANT    0.02
NON_RELEVANT       0.01
Name: proportion, dtype: float64

In [10]:
df_v2.relevance.value_counts(normalize=True)

relevance
RELEVANT           0.91
NON_RELEVANT       0.06
PARTLY_RELEVANT    0.03
Name: proportion, dtype: float64

### Inspecting non-relevant cases

Spot-check the few answers each prompt's judge marked `NON_RELEVANT`.

In [12]:
df_default[df_default.relevance == 'NON_RELEVANT']

,answer,chunk_id,question,relevance,explanation
95,{'answer': 'The provided context does not cont...,4604645_28,What is the typical serving size and compositi...,NON_RELEVANT,The generated answer does not provide any info...

In [13]:
df_v2[df_v2.relevance == 'NON_RELEVANT']

,answer,chunk_id,question,relevance,explanation
1,"{'answer': 'I don't know.', 'model_used': 'gpt...",19619306_13,What two types of coffee are combined in the p...,NON_RELEVANT,The generated answer 'I don't know' does not p...
37,"{'answer': 'I don't know.', 'model_used': 'gpt...",19619306_14,What are some alternative names for drinks tha...,NON_RELEVANT,The generated answer 'I don't know' does not p...
38,"{'answer': 'I don't know.', 'model_used': 'gpt...",604727_41,What was the percentage increase in coffee con...,NON_RELEVANT,The generated answer 'I don't know' does not p...
52,"{'answer': 'I don't know.', 'model_used': 'gpt...",604727_40,What brewing method remains the most popular f...,NON_RELEVANT,The generated answer 'I don't know' does not p...
55,"{'answer': 'I don't know.', 'model_used': 'gpt...",604727_21,How did coffee cultivation practices change st...,NON_RELEVANT,The generated answer 'I don't know' does not p...
95,"{'answer': 'I don't know', 'model_used': 'gpt-...",4604645_28,What is the typical serving size and compositi...,NON_RELEVANT,The generated answer 'I don't know' does not p...

### Save results

In [16]:
df_default.to_csv('../data/rag-eval-default.csv', index=False)
df_v2.to_csv('../data/rag-eval-v2.csv', index=False)

## Results

Compared the production prompt (`rag.prompt_template`) against a variant that
explicitly allows saying "I don't know" when the context is insufficient, judging
100 sampled questions with gpt-4o-mini as an LLM judge (NON_RELEVANT / PARTLY_RELEVANT / RELEVANT).

| Prompt | Relevant | Partly relevant | Non relevant |
|---|---|---|---|
| **Default** | **0.97** | 0.02 | 0.01 |
| "I don't know" variant | 0.91 | 0.03 | 0.06 |

The default prompt wins outright, so `rag.py`'s `prompt_template` is unchanged - no code
change needed, this run just confirms it's the better of the two.

## Round 2: safer prompt + query rewriting

A user typed "coffeine" and the bot answered with the fatal dose. Now the app fixes the question's spelling before searching, and the prompt tells the model not to swap in a different number (like a fatal dose when asked about daily intake). We test old vs. new on the same 100 questions.

A first try also told the model to "say so if the context doesn't answer". That made it give up too often: 0.87 relevant vs. 0.96 for the old setup (saved in `rag-eval-round2-first-try.csv`). So we kept only the narrow rule.

Note: the judge only checks if the answer fits the question. So an honest "I don't know" counts as NON_RELEVANT, even when it's the safer answer.

In [8]:
# the production prompt before this round, kept here so the comparison is reproducible
prompt_template_v1 = """
You're a coffee assistant. Answer the QUESTION based on the CONTEXT from our coffee database.
Use only the facts from the CONTEXT when answering the QUESTION.

QUESTION: {question}

CONTEXT:
{context}
""".strip()


def evaluate_setup(sample, prompt_template, rewrite):
    evaluations = []

    for record in tqdm(sample):
        question = record['question']
        answer_llm = rag.rag(question, prompt_template=prompt_template, rewrite=rewrite)

        prompt = prompt2_template.format(question=question, answer_llm=answer_llm['answer'])
        evaluation, _ = rag.llm(prompt)

        evaluations.append((record, answer_llm, json.loads(evaluation)))
    return evaluations

In [ ]:
df_old = to_dataframe(evaluate_setup(sample, prompt_template_v1, rewrite=False))

In [9]:
df_new = to_dataframe(evaluate_setup(sample, rag.prompt_template, rewrite=True))

  0%|          | 0/100 [00:00<?, ?it/s]

In [10]:
pd.DataFrame({
    'old (no rewrite)': df_old.relevance.value_counts(normalize=True),
    'new (rewrite + safer prompt)': df_new.relevance.value_counts(normalize=True),
}).fillna(0)

                 old (no rewrite)  new (rewrite + safer prompt)
relevance
RELEVANT                     0.96                          0.98
PARTLY_RELEVANT              0.02                          0.01
NON_RELEVANT                 0.02                          0.01

In [11]:
df_new[df_new.relevance != 'RELEVANT'][['question', 'relevance', 'explanation']]

,question,relevance,explanation
37,What are some alternative names for drinks tha...,PARTLY_RELEVANT,The generated answer provides names of coffee ...
41,What did the Supreme Court decide in the case ...,NON_RELEVANT,The generated answer explicitly states that th...

In [12]:
# the live question that triggered this round
question = "What’s the amount of coffeine that must be consumed per day?"

for name, template, rewrite in [('old', prompt_template_v1, False), ('new', rag.prompt_template, True)]:
    answer = rag.rag(question, prompt_template=template, rewrite=rewrite)
    print(f"--- {name} (search query: {answer['search_query']}) ---")
    print(answer['answer'])
    print()

--- old (search query: What’s the amount of coffeine that must be consumed per day?) ---
The context does not specify a recommended daily amount of caffeine to consume. However, it notes that a typical 6-ounce cup of coffee contains about 50–175 mg of caffeine, and lethal doses are estimated to be between 150–200 mg per kilogram of body weight. Therefore, while there is no specific amount stated for daily caffeine consumption, it is important to note that excessive intake could be harmful.

--- new (search query: What is the recommended daily intake of caffeine?) ---
The recommended amount of caffeine that should be consumed per day varies by age group and condition. For children aged 12 and under, Health Canada recommends a maximum daily caffeine intake of no more than 2.5 milligrams per kilogram of body weight. Adolescents are also advised to limit their daily caffeine intake to 2.5 mg/kg body weight.

For pregnant women, the UK Food Standards Agency recommends limiting caffeine intake to less than 200 mg per day. The American Congress of Obstetricians and Gynecologists suggests that caffeine consumption is safe up to 200 mg per day during pregnancy. For breastfeeding women or those who may become pregnant, Health Canada recommends a maximum daily caffeine intake of no more than 300 mg.

In healthy adults, moderate caffeine intake under 400 mg daily is considered modest and typically harmless.

In [13]:
df_old.to_csv('../data/rag-eval-round2-old.csv', index=False)
df_new.to_csv('../data/rag-eval-round2-new.csv', index=False)